sudo: false
branches:
  only:
    - master
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "10"
  - "12"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
  - npm run test